tasks:
  - init: |  
      composer install
      docker-compose up -d
      sleep 10
      docker-compose exec php-fpm bash .docker/install-skeleton-db.sh
      docker-compose exec php-fpm chown -R $(id -u):$(id -g) .
    command: docker-compose up -d
ports:
  - port: 80
    onOpen: open-preview
