tasks:
    init: |  
      composer install
      docker-compose up -d
      docker-compose exec php-fpm bash .docker/install-skeleton-db.sh
    command: docker-compose up -d
ports:
  - port: 80
    onOpen: open-preview
